default:
  elementpath: false
  height: 500
  plugins:
    - image
    - link
    - autoresize
    - colorpicker
    - textcolor
    - preview
    - autolink
  resize: false
  statusbar: false
  toolbar:
    - 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image'
    - 'forecolor backcolor | formatselect fontselect fontsizeselect | cut copy paste'
